//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CustomerBooking
    {
        public int BId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Checkin { get; set; }
        public System.DateTime Checkout { get; set; }
        public string City { get; set; }
        public int HId { get; set; }
        public int RDetId { get; set; }
    
        public virtual T_Users T_Users { get; set; }
        public virtual T_HotelDetails T_HotelDetails { get; set; }
        public virtual T_HotelRoomDetails T_HotelRoomDetails { get; set; }
    }
}
