//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HotelDetails
    {
        public T_HotelDetails()
        {
            this.T_CustomerBooking = new HashSet<T_CustomerBooking>();
            this.T_HotelRoomDetails = new HashSet<T_HotelRoomDetails>();
        }
    
        public int HId { get; set; }
        public string HName { get; set; }
        public string HAddress { get; set; }
        public int NRooms { get; set; }
        public int ACRooms { get; set; }
        public int NonACRooms { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<T_CustomerBooking> T_CustomerBooking { get; set; }
        public virtual ICollection<T_HotelRoomDetails> T_HotelRoomDetails { get; set; }
    }
}
